DOC: fixes broken adonis link
qiime2/q2-diversity pull request #311
Opened 2021-06-10 21:19 UTC by ChrisKeefe

closes #310 

Search didn't turn up any other `oulu.fi` URLs.

2021-06-16 19:41 UTC, lizgehret requested changes
Hey @ChrisKeefe! Looks like there is a space missing between a couple of words in your change - other than that, it lgtm!

2021-06-16 19:41 UTC, lizgehret commented on q2_diversity/plugin_setup.py
> +                 'more details, consult the reference manual available'
```suggestion
                 'more details, consult the reference manual available '
```

2021-06-16 23:17 UTC, ChrisKeefe commented on q2_diversity/plugin_setup.py
> +                 'more details, consult the reference manual available'
:facepalm:

2021-06-17 16:53 UTC, lizgehret approved these changes
lgtm!

2021-06-17 16:54 UTC, merged