ENH: add random_state param in dim reduction methods
qiime2/q2-diversity pull request #323
Opened 2022-02-16 09:18 UTC by misialq

This PR introduces a `random_state` parameter to the two dimensionality reduction methods: tSNE and UMAP for better result reproducibility.

2022-02-16 16:51 UTC, ebolyen requested changes

2022-02-16 16:51 UTC, ebolyen commented on q2_diversity/_ordination.py
> +         random_state: int = 1) -> skbio.OrdinationResults:
This should default to `None` so that it's optional (it's also a valid input for sklearn with the expected semantics).

2022-02-16 16:51 UTC, ebolyen commented on q2_diversity/_ordination.py
> +         random_state: int = 1) -> skbio.OrdinationResults:
Same here (umap package also supports `None`).

2022-02-17 08:44 UTC, misialq commented
Thanks for pointing those out @ebolyen, all's updated!

2022-02-17 17:21 UTC, ebolyen approved these changes
Thanks @misialq!

2022-02-17 17:21 UTC, merged